CREATE TABLE IF NOT EXISTS `saig_google_geodata` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Ref_Id` varchar(20) NOT NULL,
  `Ref_Type` varChar(20) NOT NULL,
  `Name` varchar(127),
  `Sf_Address_1` varchar(127),
  `Sf_Address_2` varchar(127),
  `Sf_Address_3` varchar(127),
  `Sf_City` varchar(127),
  `Sf_State` varchar(127),
  `Sf_Country` varchar(127),
  `Sf_PostCode` varchar(20),
  `Sf_Latitude` double(18,10),
  `Sf_Longitude` double(18,10),
  `Google_Address_1` varchar(127),
  `Google_Address_2` varchar(127),
  `Google_Address_3` varchar(127),
  `Google_City` varchar(127),
  `Google_State` varchar(127),
  `Google_Country` varchar(127),
  `Google_PostCode` varchar(20),
  `Google_Latitude` double(18,10),
  `Google_Longitude` double(18,10),
  PRIMARY KEY (`Id`),
  UNIQUE(Ref_Id)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;