use salesforce;

insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Royalties','PS','2014-07-01',96384.01);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Royalties','PS','2014-08-01',62392.59);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Royalties','PS','2014-09-01',128566.47);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Royalties','PS','2014-10-01',54217.15);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Royalties','PS','2014-11-01',91573.06);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Royalties','PS','2014-12-01',67507.42);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Royalties','PS','2015-01-01',59701.02);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Royalties','PS','2015-02-01',97376.2);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Royalties','PS','2015-03-01',53794.54);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Royalties','PS','2015-04-01',85968.53);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Royalties','PS','2015-05-01',111886.25);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Royalties','PS','2015-06-01',85102.13);

insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','PS','2014-07-01',36348.57);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','PS','2014-08-01',39476.67);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','PS','2014-09-01',80871.16);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','PS','2014-10-01',37420.07);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','PS','2014-11-01',81136.76);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','PS','2014-12-01',96264.68);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','PS','2015-01-01',27178.5);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','PS','2015-02-01',37810.41);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','PS','2015-03-01',31793);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','PS','2015-04-01',57630);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','PS','2015-05-01',67672);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','PS','2015-06-01',46723);

insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','Food','2014-07-01',468791.75);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','Food','2014-08-01',437688.76);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','Food','2014-09-01',495202.99);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','Food','2014-10-01',491030);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','Food','2014-11-01',421268.69);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','Food','2014-12-01',287677.05);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','Food','2015-01-01',230567.98);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','Food','2015-02-01',382486.71);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','Food','2015-03-01',404734.59);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','Food','2015-04-01',397834.04);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','Food','2015-05-01',369532.82);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','Food','2015-06-01',427664.85);

insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','MS','2014-07-01',2253781.85);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','MS','2014-08-01',2106683.58);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','MS','2014-09-01',2392689.21);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','MS','2014-10-01',2391327.77);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','MS','2014-11-01',2002993.88);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','MS','2014-12-01',1289716.37);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','MS','2015-01-01',1042158.9);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','MS','2015-02-01',2077666.33);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','MS','2015-03-01',2237826.51);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','MS','2015-04-01',1961216.67);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','MS','2015-05-01',2204098.75);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Audit Revenue','MS','2015-06-01',2086831.85);

insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','PS','2014-07-01',759392.18);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','PS','2014-08-01',734200.75);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','PS','2014-09-01',747823.02);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','PS','2014-10-01',802765.19);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','PS','2014-11-01',733305.36);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','PS','2014-12-01',750237.82);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','PS','2015-01-01',768416.13);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','PS','2015-02-01',685705.62);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','PS','2015-03-01',767685.15);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','PS','2015-04-01',729106.08);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','PS','2015-05-01',768435.99);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','PS','2015-06-01',740820.19);

insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','Food','2014-07-01',70963.24);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','Food','2014-08-01',74121.05);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','Food','2014-09-01',69600.93);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','Food','2014-10-01',72860.37);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','Food','2014-11-01',68870.21);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','Food','2014-12-01',69532.42);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','Food','2015-01-01',71409.37);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','Food','2015-02-01',63308.82);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','Food','2015-03-01',70573.57);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','Food','2015-04-01',67428.52);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','Food','2015-05-01',68345.16);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','Food','2015-06-01',64997.24);

insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','MS','2014-07-01',608794.54);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','MS','2014-08-01',617225.42);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','MS','2014-09-01',594163.81);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','MS','2014-10-01',613365.4);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','MS','2014-11-01',587862.91);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','MS','2014-12-01',612072.97);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','MS','2015-01-01',608606.09);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','MS','2015-02-01',552420.68);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','MS','2015-03-01',615522.21);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','MS','2015-04-01',582173.27);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','MS','2015-05-01',603343.9);
insert into sf_data (CreateDate, Region, DataType, DataSubType, RefName, RefDate, RefValue) VALUES (now(), 'Australia ', 'PeopleSoft','Registration Fee','MS','2015-06-01',564617.87);
